apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: devops-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  JWT_SECRET: "Y2hhbmdlLW1lLWxhdGVy"