apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/platform
  - api-gateway-route.yaml
namespace: devops-platform

labels:
  - pairs:
      environment: local
images:
- name: ghcr.io/abhishek3100/devops-microservices-platform/api-gateway
  newTag: latest

- name: ghcr.io/abhishek3100/devops-microservices-platform/user-service
  newTag: latest

- name: ghcr.io/abhishek3100/devops-microservices-platform/task-service
  newTag: latest

- name: ghcr.io/abhishek3100/devops-microservices-platform/notification-service
  newTag: latest

- name: ghcr.io/abhishek3100/devops-microservices-platform/frontend
  newTag: latest