apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: devops-platform

labels:
  - pairs:
      environment: local

images:
  - name: notification-service
    newName: ghcr.io/abhishek3100/devops-microservices-platform/notification-service
    newTag: latest