apiVersion: v1
kind: ConfigMap

metadata:
  name: platform-config
  namespace: devops-platform

data:

  USER_SERVICE_HOST: user-service
  USER_SERVICE_PORT: "4000"

  TASK_SERVICE_HOST: task-service
  TASK_SERVICE_PORT: "50051"

  NOTIFICATION_HOST: notification-service
  NOTIFICATION_PORT: "50052"