apiVersion: v1
kind: Service
metadata:
  name: user-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - port: 4000
      targetPort: 4000