apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: default
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    type: Kubernetes