# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x04task\"1\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"\"\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\".\n\x12\x43reateTaskResponse\x12\x18\n\x04task\x18\x01 \x01(\x0b\x32\n.task.Task\"\x11\n\x0fGetTasksRequest\"-\n\x10GetTasksResponse\x12\x19\n\x05tasks\x18\x01 \x03(\x0b\x32\n.task.Task2\x89\x01\n\x0bTaskService\x12?\n\nCreateTask\x12\x17.task.CreateTaskRequest\x1a\x18.task.CreateTaskResponse\x12\x39\n\x08GetTasks\x12\x15.task.GetTasksRequest\x1a\x16.task.GetTasksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=20
  _globals['_TASK']._serialized_end=69
  _globals['_CREATETASKREQUEST']._serialized_start=71
  _globals['_CREATETASKREQUEST']._serialized_end=105
  _globals['_CREATETASKRESPONSE']._serialized_start=107
  _globals['_CREATETASKRESPONSE']._serialized_end=153
  _globals['_GETTASKSREQUEST']._serialized_start=155
  _globals['_GETTASKSREQUEST']._serialized_end=172
  _globals['_GETTASKSRESPONSE']._serialized_start=174
  _globals['_GETTASKSRESPONSE']._serialized_end=219
  _globals['_TASKSERVICE']._serialized_start=222
  _globals['_TASKSERVICE']._serialized_end=359
# @@protoc_insertion_point(module_scope)
