# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\"&\n\x13NotificationRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x14NotificationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2p\n\x13NotificationService\x12Y\n\x10SendNotification\x12!.notification.NotificationRequest\x1a\".notification.NotificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONREQUEST']._serialized_start=36
  _globals['_NOTIFICATIONREQUEST']._serialized_end=74
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=76
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=114
  _globals['_NOTIFICATIONSERVICE']._serialized_start=116
  _globals['_NOTIFICATIONSERVICE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
