apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: devops-dev
            path: k8s/overlays/dev
            
          - env: local
            namespace: devops-platform
            path: k8s/overlays/local
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: environment
              operator: In
              values:
                - local
        - matchExpressions:
            - key: environment
              operator: In
              values:
                - dev

  template:
    metadata:
      name: "platform-{{env}}"
      labels:
        environment: "{{env}}"
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          api-gateway=ghcr.io/abhishek3100/devops-microservices-platform/api-gateway
          frontend=ghcr.io/abhishek3100/devops-microservices-platform/frontend
          user-service=ghcr.io/abhishek3100/devops-microservices-platform/user-service
          task-service=ghcr.io/abhishek3100/devops-microservices-platform/task-service
          notification-service=ghcr.io/abhishek3100/devops-microservices-platform/notification-service
        argocd-image-updater.argoproj.io/commonUpdateSettings: update-strategy=newest-build
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main
    spec:
      project: platform
      source:
        repoURL: https://github.com/abhishek3100/devops-microservices-platform.git
        targetRevision: main
        path: k8s/overlays/{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true