apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: devops-dev
            path: k8s/overlays/dev
            
          - env: local
            namespace: devops-platform
            path: k8s/overlays/local

  template:
    metadata:
      name: "platform-{{env}}"
    spec:
      project: platform
      source:
        repoURL: https://github.com/abhishek3100/devops-microservices-platform.git
        targetRevision: main
        path: k8s/overlays/{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true