apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces
  - config
  # - api-gateway
  - user-service
  # - task-service
  - notification-service
  # - frontend
  # - gateway
  # - monitoring