kustomize:
  images:
  - ghcr.io/abhishek3100/devops-microservices-platform/api-gateway:latest
  - ghcr.io/abhishek3100/devops-microservices-platform/frontend:latest
  - ghcr.io/abhishek3100/devops-microservices-platform/user-service:latest
  - ghcr.io/abhishek3100/devops-microservices-platform/task-service:latest
  - ghcr.io/abhishek3100/devops-microservices-platform/notification-service:latest
